service: vote

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    VOTES_TABLE: "votes"
    AGREGATE_VOTES_TABLE: "agregate-votes"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: 
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.VOTES_TABLE}"
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: 
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.AGREGATE_VOTES_TABLE}"

functions:
  vote:
    handler: handler.vote
    events:
      - http:
          path: vote
          method: post
          cors: true
  voteTriggered:
    handler: handler.trigger
    events:
      - stream: ${file(stream_arn.yml):stream}
  votes:
    handler: handler.votes
    events:
      - http:
          path: votes
          method: get
          cors: true
  clean:
    handler: handler.clean
    events:
      - http:
          path: votes/clean
          method: get
          cors: true